#!/usr/bin/env bash

set_chrome_dev_tools_theme() {
	local dir=$1
	local theme=$2
	local style=$3

	rm -rf "$HOME/Library/Application Support/Google/Chrome/Default/User StyleSheets/*"
	ln -s "${dir}/chrome-devtools/base16-${theme}.${style}.css" "$HOME/Library/Application Support/Google/Chrome/Default/User StyleSheets/Custom.css"
}

set_chrome_dev_tools_theme "$@"
