#!/usr/bin/env bash

set_marked_theme() {
	local dir=$1
	local theme=$2
	local dest="$HOME/Library/Application Support/Marked/Custom CSS/"

	if [[ ! -d "$dest" ]]; then
		mkdir -p "$dest"
	else
		rm -rf "$dest/*"
	fi
	
	ln -s "${dir}/marked/base16-${theme}.css" "$dest/base16-${theme}.css"
}

set_marked_theme "$@"
