#!/usr/bin/env bash

set_osx_color_palette_theme() {
	local dir=$1
	local theme=$2

	rm -rf "$HOME/Library/Colors/*.clr"
	open "${dir}/osx-color-palette/base16-${theme}.clr"
}

set_osx_color_palette_theme "$@"

