#!/usr/bin/env bash

set_vim_theme() {
	shift
	local theme=$1
	local style=$2
	local dest="$HOME/.vim/settings/theme.vim"

	rm -rf "$dest"
	echo "set background=${style}" >> "$dest"
	echo "silent! colorscheme base16-${theme}" >> "$dest"
}

set_vim_theme "$@"
