#!/usr/bin/env bash

set_xcode_theme() {
	local dir=$1
	local theme=$2
	local style=$3

	mkdir -p "$HOME/Library/Developer/Xcode/UserData/FontAndColorThemes"
	rm -rf "$HOME/Library/Developer/Xcode/UserData/FontAndColorThemes/*"
	ln -s "${dir}/xcode4/base16-${theme}.${style}.dvtcolortheme" "$HOME/Library/Developer/Xcode/UserData/FontAndColorThemes/"
}

set_xcode_theme "$@"
