#!/usr/bin/env bash

set_xcode_theme() {
	local dir=$1
	local theme=$2
	local style=$3
	local dest="$HOME/Library/Developer/Xcode/UserData/FontAndColorThemes"

	if [[ ! -d "$dest" ]]; then
		mkdir -p "$dest"
	fi

	rm -rf "$dest/*"
	mv "${dir}/xcode4/base16-${theme}.${style}.dvtcolortheme" "$dest/base16-${theme}.${style}.dvtcolortheme"
}

set_xcode_theme "$@"
